<template>
  <div id="app">
    <section class="section">
    <div class="container">
      <h1 class="title">Textractor WebSocket Client</h1>
      <button class="button is-primary" v-if="buttonConnectVisibility" :disabled="buttonDisabled" @click="connect()">Connect</button>
      <button class="button is-danger" v-if="!buttonConnectVisibility" @click="disconnect()">Disconnect</button>
      <button class="button is-warning" @click="clear()">Clear</button>
    </div>
    </section>
    <section class="messages">
      <div class="container">
        <div class="card fade-in-fwd" v-for="msg in messages" :key='msg'>
          <div class="card-content">
            {{ msg }}
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
const CONNTECTION_STATUS = {
  DISCONNTECT: 0,
  CONNECTING: 1,
  CONNECTED: 2
};
const MAX_AMOUNT = 50;

export default {
  name: 'app',
  data: function() {
    return {
      status: CONNTECTION_STATUS.DISCONNTECT,
      ws: null,
      messages: [ ]
    }
  },
  methods: {
    clear() {
      this.messages.length = 0;
    },

    connect() {
      this.status = CONNTECTION_STATUS.CONNECTING
      this.ws = new WebSocket('ws://localhost:1234')
      this.ws.addEventListener('close', this.eventWebSocketClosed);
      this.ws.addEventListener('message', this.eventWebSocketMessage);
      this.ws.addEventListener('open', this.eventWebSocketOpen);
      this.ws.addEventListener('error', this.eventWebSocketError);
    },

    disconnect() {
      if (this.ws) {
        this.ws.close();
      }
    },

    eventWebSocketClosed() {
      this.status = CONNTECTION_STATUS.DISCONNTECT
      this.ws = null;
    },

    eventWebSocketMessage(event) {
      this.messages.unshift(event.data);
      if (this.messages.length > MAX_AMOUNT)
        this.messages.pop();
    },

    eventWebSocketOpen() {
      this.status = CONNTECTION_STATUS.CONNECTED;
    },

    eventWebSocketError() {
      this.status = CONNTECTION_STATUS.DISCONNTECT;
    }
  },
  computed: {
    buttonConnectVisibility() {
      return this.status < CONNTECTION_STATUS.CONNECTED
    },

    buttonDisabled() {
      return this.status === CONNTECTION_STATUS.CONNECTING
    }
  }
}
</script>

<style>
#app, #app .button {
  font-family: 'Kosugi Maru', sans-serif;
}
.card {
  font-size: 1.3em;
  margin-top: 1em;
}
.card:first-of-type {
  margin-top: 0em;
}
.button.is-warning {
  margin-left: 1em;
}
.fade-in-fwd {
	animation: fade-in-fwd 0.6s cubic-bezier(0.390, 0.575, 0.565, 1.000) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-11-23 5:28:59
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-in-fwd
 * ----------------------------------------
 */
@keyframes fade-in-fwd {
  0% {
    transform: translateZ(-80px);
    opacity: 0;
  }
  100% {
    transform: translateZ(0);
    opacity: 1;
  }
}
</style>
